### ISSUE TITLE
gen12 support is missing

### ISSUE THREAD

**Issue by dvrogozh** [intel/cm-compiler#19]
See https://github.com/Intel-Media-SDK/MediaSDK/issues/2206

Media projects:
* https://github.com/intel/media-driver
* https://github.com/Intel-Media-SDK/MediaSDK
Provide sources of EU kernels for a range of platforms including Gen12. We need corresponding support to be available in open source cm compiler version. Could you, please, add since it seems to be missing? Quoting the msdk filed issue:

> It is currently not possible to build v20.1.1 with -DBUILD_KERNELS=on as the latest published cm-compiler release (Release_20190717) is missing gen 12 VME support (gen12_vme.h is empty). The genx_simple_me and genx_me kernels fail to build.

**Comment by cmc-rep** [comment]
I will try to enable Gen12.  Could you provide me the test cases? You may directly send it to my Intel email if necessary.

**Comment by george-norton** [comment]
You can build the mediasdk simple_me kernel like this:
```
#!/bin/bash

curl https://raw.githubusercontent.com/Intel-Media-SDK/MediaSDK/intel-mediasdk-20.1.1/_studio/mfx_lib/genx/h264_encode/src/genx_simple_me.cpp -o genx_simple_me.cpp
for genx in gen11 gen12
do
	mkdir -p ${genx}
	cd ${genx}
	cmc -c -Qxcm -Qxcm_release -Qxcm_print_asm_count -menableiga -mCM_init_global -mCM_printregusage -Dtarget_${genx} -Qxcm_jit_target=${genx} ../genx_simple_me.cpp -o genx_simple_me.isa 2>&1 | tee build.log
	cd ..
done
```

The gen11 build works, but the gen12 build does not.

**Comment by cmc-rep** [comment]
Done.  The target for cmc is GEN12LP or TGLLP

**Comment by cmc-rep** [comment]
You also need the GenX_IR that supports Gen12, which should come with IGC build

**Comment by george-norton** [comment]
Thank you for your quick work!

I updated my IGC build and a quick test seems to show that gen12lp now builds, but now I am not able to build the MediaSDK as [Cannon Lake support has been recently removed](https://github.com/intel/intel-graphics-compiler/commit/6e9f0af19184cdc3f94c32c23692eaccd3b0ef20) from GenX_IR but still exists in the MediaSDK.

It isn't clear to me if gen10 should be removed from the MediaSDK or put back into the GenX_IR tool..

**Comment by cmc-rep** [comment]
You can find old GenX_IR in cm developement package in cm-compiler release tab that may still support Cannon Lake.  I am trying to find out the right answer to your question in the mean time.

**Comment by cmc-rep** [comment]
Our expert says: we should removed Cannon Lake from MediaSDK as well

**Comment by george-norton** [comment]
Thanks, I guess it might need to be removed from the media-driver too.

**Comment by dvrogozh** [comment]
> Thanks, I guess it might need to be removed from the media-driver too.

@george-norton : yep - this is eventual consideration. Give is couple of days, we will discuss internally and let you know the outcome.
